### ISSUE TITLE
How to publish this mashup

### ISSUE THREAD

**Issue by alexbjorlig** [fkabinoff/qlik-lars#1]
Hi Lars. 

After doing npm install and grunt build, what do I do to see the mashup in the browser?

**Comment by fkabinoff** [comment]
So this template doesn't include a server component. You'll have to host the files in some manner. There's really 2 options.

Option 1 - Host the files on some server that's different than your Qlik Sense server.
You can host the files on any server, local or otherwise. Just make sure that the host is whitelisted with the Qlik Sense virtual proxy you are using. You'll also want to make sure that the links for the Qlik Sense assets in index.html, as well as the config in main.js are pointing to your Qlik Sense server.

Option 2 - Host the files with your Qlik Sense server
You can import the project as an extension to your Qlik Sense server. You'll need a .qext file though.
